apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.productsapi.name | lower }}
  labels:
    app: {{ .Values.productsapi.name }}
    chart: {{ template "AksDevOpsSample.chart" . }}
    draft: {{ default "draft-app" .Values.draft }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.productsapi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.productsapi.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.productsapi.name }}
        draft: {{ default "draft-app" .Values.draft }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.productsapi.image.repository }}:{{ .Values.productsapi.image.tag }}"
          imagePullPolicy: {{ .Values.productsapi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.productsapi.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.productsapi.probes.livenessProbe }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.productsapi.probes.readinessProbe }}
              port: http
          {{- end }}
          env:
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "AksDevOpsSample.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
